# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfFux3czt_KKkQT4dWdllGO3IdMelJiY
"""

# OSS개발 개인과제
# 주제: 유방암 데이터셋을 활용한 악성/양성 분류 모델 구현

# 1. 필요한 라이브러리 불러오기
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 2. 데이터셋 로드
data = load_breast_cancer()

X = data.data      # 입력 데이터
y = data.target    # 정답 데이터

print("데이터셋 이름: Breast Cancer Wisconsin Dataset")
print("전체 데이터 개수:", X.shape[0])
print("특성 개수:", X.shape[1])
print("분류 클래스:", data.target_names)

# 3. train/test split
# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 나눔
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("학습 데이터 개수:", X_train.shape[0])
print("테스트 데이터 개수:", X_test.shape[0])

# 4. 머신러닝 모델 생성
# RandomForestClassifier: 여러 개의 결정트리를 이용해 분류하는 모델
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# 5. 모델 학습
model.fit(X_train, y_train)

# 6. 예측
y_pred = model.predict(X_test)

# 7. 정확도 출력
accuracy = accuracy_score(y_test, y_pred)

print("\n모델: RandomForestClassifier")
print("정확도:", accuracy)
print("정확도(%):", round(accuracy * 100, 2), "%")

# 8. 추가 평가 결과 출력
print("\n혼동행렬:")
print(confusion_matrix(y_test, y_pred))

print("\n분류 보고서:")
print(classification_report(y_test, y_pred, target_names=data.target_names))
